---
title: Kleurinvoer instellen met pipet
hero_image: images/banner.png
description: Stel de kleurinvoer van Waarnemen- en Pen-blokken in met de pipet.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Kleurinvoer instellen met pipet
