title: scratch3-set-block-input-colour-with-eyedropper
hero_image: images/banner.png
description: scratch3-set-block-input-colour-with-eyedropper description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
