---
title: Gosod mewnbwn lliw gyda'r diferydd llygad
hero_image: images/banner.png
description: Gosod mewnbwn lliw y blociau Synhwyro a Phin gyda'r diferydd llygad.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Gosod mewnbwn lliw gyda'r diferydd llygad
