---
title: Definir entrada de cores com conta-gotas
hero_image: images/banner.png
description: Defina a entrada de cores dos blocos Sensor e Caneta com o conta-gotas.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Definir entrada de cores com conta-gotas
