---
title: Establece la entrada de color con el gotero
hero_image: images/banner.png
description: Establece el color de los bloques de Sensores y Lápiz con el gotero.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Establece el color con el gotero
