---
title: Ustaw kolor za pomocą próbnika koloru
hero_image: images/banner.png
description: Ustaw kolor bloków Sensing i Pen za pomocą próbnika koloru.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Ustaw kolor za pomocą próbnika koloru
