---
title: Set colour input with eyedropper
hero_image: images/banner.png
description: Set the colour input of Sensing and Pen blocks with the eyedropper.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Set colour input with eyedropper
