---
title: Définir l'entrée de couleur avec la pipette
hero_image: images/banner.png
description: Définir l'entrée de couleur des blocs Capteurs et stylo avec la pipette.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Définir l'entrée de couleur avec la pipette
