---
title: Imposta l'input dei colori con il contagocce
hero_image: images/banner.png
description: Imposta l'input dei colori dei blocchi Sensori e Penna con il contagocce.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Imposta l'input dei colori con il contagocce
